### ISSUE TITLE
Guzzle 7 Support

### ISSUE THREAD

**Issue by LukeAbell** [PromPHP/prometheus_client_php#11]
Could guzzle 7 support be added? Laravel 8 requires it now.

**Comment by LKaemmerling** [comment]
Hey @LukeAbell,

This library does not require Guzzle anymore (with v2, which is a breaking release because of the removed Pushgateway Support). If you need Pushgateway Support there is a new package. Have a look at the Readme :)

**Comment by LukeAbell** [comment]
@LKaemmerling can you remove it from the composer.json then? That’s what’s blocking the update for me. https://github.com/PromPHP/prometheus_client_php/blob/1e046c09533733c2988a81bfaaab7d2855d7c2e8/composer.json#L23

**Comment by LKaemmerling** [comment]
Actually as this is only a requirement for development, it should work without removing it. We use Guzzle for the tests.

How did you require the lib?

**Comment by LukeAbell** [comment]
@LKaemmerling My project requires guzzle 7 so I think there’s a mismatch in package versions that’s breaking it.

**Comment by LKaemmerling** [comment]
@LukeAbell i just released v2.1.1 which allows guzzle 7 within the dev dependencies.

**Comment by LukeAbell** [comment]
@LKaemmerling Thank you!! 💯
