### ISSUE TITLE
BC on RegistryInterface in getMetricFamilySamples() method from 2.7.0

### ISSUE THREAD

**Issue by javespi** [PromPHP/prometheus_client_php#117]
Hello,

I have a custom implementation for `Prometheus\RegistryInterface` class which since 2.7.0 requires me to implement the method `getMetricFamilySamples()` with an argument:

```
PHP Fatal error:  Declaration of Javespi\MyCollectorRegistry::getMetricFamilySamples(): array
must be compatible with Prometheus\RegistryInterface::getMetricFamilySamples(bool $sortMetrics = true): array
```

It looks like the BC was introduced in this PR:
- https://github.com/PromPHP/prometheus_client_php/pull/108

I am going to try to create a pull-request to solve it without losing the new feature.

Cheers

**Comment by LKaemmerling** [comment]
Hey @javespi,

thank you for the headsup. I just released a new version (2.7.1) with your changes.
