### ISSUE TITLE
How InMemory() Work ?

### ISSUE THREAD

**Issue by Alitindrawan24** [PromPHP/prometheus_client_php#125]
I'm currently trying to use this package and use InMemory() to store metrics. But whenever I access the /metrics endpoint, all metrics are empty. Previously I tried with php Redis and it worked fine. Thank You

**Comment by LKaemmerling** [comment]
Hey @Alitindrawan24,

sorry for the late reply:

The InMemory Storage stores the metrics only in an array, so it is only available as long as the process is living (e.g. only when you make the request).

**Comment by Alitindrawan24** [comment]
Hello @LKaemmerling okay thank you for the explanation
