### ISSUE TITLE
Additional Maintainers

### ISSUE THREAD

**Issue by LKaemmerling** [PromPHP/prometheus_client_php#13]
Hello everyone whoever reads this,

I'm searching for additional Maintainers for this important project. If you use the client within production and want to help, just write under this issue and will chat a bit about it.

- Lukas

**Comment by mnsami** [comment]
hello, I don't use it, but I like to jump in and volunteer.

**Comment by LKaemmerling** [comment]
Hey @mnsami,

thank you for your offer! I would like to have someone who has already knowledge about Prometheus and use Prometheus (and this library) in production. Otherwise, it might be hard to understand this library and the things that may come in.

**Comment by mnsami** [comment]
Sure, I understand and respect your wish, let me know anytime if you change your mind, as I am still interested.

I know there might be a learning curve for me, but I am a fast learner.

Thanks!

**Comment by rdohms** [comment]
@LKaemmerling put me down to help. I'll be looking for another SVMK member to be a fallback and we will be looking to see how we can put in some work.

**Comment by nickpoulos** [comment]
We can help out too.  We are using Prometheus/Grafana in prod but having issues finding a solid, well maintained Prometheus package for PHP.

**Comment by LKaemmerling** [comment]
Hey @nickpoulos, 

this would be great! If you want, you can join our slack channel (https://join.slack.com/t/promphp/shared_invite/zt-iqbocinr-R809BvkEhjuC9W6RRoOofA), and then we can talk about it :)


When you join us, I guess we have "enough" for the core maintaining team (@rdohms and me currently, @bracki as a fallback).

I will close the issue for now, if you find this issue and want to contribute, feel free to do so! We just want to have a "small" core team that can react to things fast :)
