### ISSUE TITLE
Were is the connection to prometheus?

### ISSUE THREAD

**Issue by prdatur** [PromPHP/prometheus_client_php#14]
Hi,

Sorry I do not get it, what is this library for?
I assumed it is a client to the prometheus db, but I can not find any configuration to setup the connection to the database server, nor could I find any code with requests to a database.

Is there any documentation to use this library with an actual database?

My requirement is to connect to our PromQL time series database (currently testing VictoriaMetrics ) and get some data / insert new data / delete old data.

**Comment by LKaemmerling** [comment]
This library basically makes it possible to output any metric in the correct Prometheus format. There is no way to "access" the actual TSDB with this lib (accessing the real tsdb isn't recommended by the Prometheus guys, you should always use the admin API)

**Comment by prdatur** [comment]
I understand that i should not access the underlaying database directly, but I miss in this library something like `->getData(filter, date_from. date_to)` which executes a query to the admin webinterface api and get back the results, or `->insert(fields, date, value)` which inserts the data into the prometheus system with the api.
I thought Prometheus is like other time based database like influx.
Currently I must assume this library only creates a format, which I can get/post manually to the api?

**Comment by LKaemmerling** [comment]
This lib just provides the correct format. Prometheus then scrapes the page itself (on a GET `metrics` endpoint per default).


```php
use Prometheus\CollectorRegistry;
use Prometheus\RenderTextFormat;
use Prometheus\Storage\Redis;


$adapter = new Prometheus\Storage\InMemory();
$registry = new CollectorRegistry($adapter);

// Some gauges
$gauge = $registry->registerGauge('test', 'some_gauge', 'it sets', ['type']);
$gauge->set(123, ['blue']);

$renderer = new RenderTextFormat();
$result = $renderer->render($registry->getMetricFamilySamples());

header('Content-type: ' . RenderTextFormat::MIME_TYPE);
echo $result;
```

Prometheus itself scrapes this exporter/endpoint then and provides the data through the promql API. 

This library is not intended to access Prometheus, it is intended to be reached *from* Prometheus.

**Comment by LKaemmerling** [comment]
Prometheus is not like Influx, Prometheus doesn't provide a database like Influx, Prometheus scrapes it's Exporters/Targets (pull based approach), Influx accepts data from other this (Push based approach)

**Comment by prdatur** [comment]
Thanks for this information, helped alot :)
