### ISSUE TITLE
Implement better interfaces

### ISSUE THREAD

**Issue by rdohms** [PromPHP/prometheus_client_php#15]
I had originally submitted this PR to Jimdo library: https://github.com/Jimdo/prometheus_client_php/pull/61

In a general gist it adds better interfacing to the boundaries to allow projects to better handle injection and clean their dependencies.

This one adds an interface to the Registry and the Renderer.

@LKaemmerling is this something you would be open to improving? i would be willing to invest time in this with you.

**Comment by LKaemmerling** [comment]
@rdohms looks like a valuable improvement!

**Comment by rdohms** [comment]
Alright, I'll put in the work to port that over and see what else we can improve.

**Comment by rdohms** [comment]
Closed by #16
