### ISSUE TITLE
Warning: Redis::connect(): php_network_getaddresses: getaddrinfo for redis failed in C:\...\vendor\promphp\prometheus_client_php\src\Prometheus\Storage\Redis.php on line 226

### ISSUE THREAD

**Issue by AzizxonZufarov** [PromPHP/prometheus_client_php#155]
Good day!
When I open Yii2 advanced project in the browser, I get this error:
Warning: Redis::connect(): php_network_getaddresses: getaddrinfo for redis failed: ���� ���� ����������. in C:\OSPanel\domains\localhost\mysite\vendor\promphp\prometheus_client_php\src\Prometheus\Storage\Redis.php on line 226
How can I fix this?
Thanks!

**Comment by LKaemmerling** [comment]
Hey @AzizxonZufarov,

this is an issue with your local setup, most likely your DNS servers are not reachable. So this is sadly nothing we can help with.
