### ISSUE TITLE
Basic in memory store not working?

### ISSUE THREAD

**Issue by akmur** [PromPHP/prometheus_client_php#160]
hello, I hope somebody can help me understand what I'm doing wrong

I was trying to implement inMemory statistics, and I have setup a super basic slim application like so:

```
<?php

use Slim\Factory\AppFactory;
use Prometheus\Storage\InMemory;
use Prometheus\CollectorRegistry;
use Prometheus\RenderTextFormat;

require __DIR__ . '/vendor/autoload.php';

// Create Slim app
$app = AppFactory::create();

// Prometheus setup
$registry = new CollectorRegistry(new InMemory());
$counter = $registry->registerCounter('test', 'some_counter', 'it increases', ['type']);

// Define a simple route
$app->get('/', function ($request, $response, $args) use ($counter) {
    $counter->incBy(3, ['blue']);
    $response->getBody()->write("Hello, world!");
    return $response;
});

// Define a metrics route
$app->get('/metrics', function ($request, $response, $args) use ($registry) {
    $renderer = new RenderTextFormat();
    $result = $renderer->render($registry->getMetricFamilySamples());

    $response->getBody()->write($result);
    return $response->withHeader('Content-Type', $renderer::MIME_TYPE);
});

// Run the app
$app->run();
```

When I hit `/` I get correctly an Hello World, but when I hit `/metrics` I get always the same result

```
# HELP php_info Information about the PHP environment.
# TYPE php_info gauge
php_info{version="8.3.6"} 1
```

Do you know what I am doing wrong? Thanks for your time

**Comment by LKaemmerling** [comment]
The In-Memory Adapter is not useful for production setups, as it will lose the metrics within a request. The recommendation is to use Redis (or APCng) as those are persistent even between requests. This has nothing todo with the implementation of the In-Memory Adapter and is rather because of the Memory Model from PHP (No memory is shared between requests).

**Comment by akmur** [comment]
Ok thanks, I realize that it doesn;t work by itself but it needs some sort of persistence. Thanks for your help.
