### ISSUE TITLE
Broken auth for Redis/RedisNg with latest 2.13 release

### ISSUE THREAD

**Issue by breda** [PromPHP/prometheus_client_php#171]
After `v2.13.0` was released, which includes PR #167, 
it introduced a bug where if the username for `Redis` and `RedisNg` auth is empty, the auth step fails.

Example, I have the same on a project i'm working on (Symfony, using `artprima/prometheus-metrics-bundle`):
```
PROMETHEUS_METRIC_STORAGE_DSN=redis://:secret@redis:6379/1
```

This is a pretty common example where we only set the password, and leave the username empty.
In such case, the options array passed to Redis/RedisNg will include `user` but it'll be an empty string.

This causes an error: `WRONGPASS invalid username-password pair or user is disabled.`

**Comment by breda** [comment]
Hey @LKaemmerling I think this should be looked at ASAP :)

**Comment by LKaemmerling** [comment]
@breda thank you! I just released your fix as v2.13.1. Thank you!

**Comment by breda** [comment]
Thank you for your quick response, I should have mentioned you sooner!
