### ISSUE TITLE
Support floats in Counters

### ISSUE THREAD

**Issue by foosinn** [PromPHP/prometheus_client_php#20]
Hey,

is there a specific reason, that the counter does not support floats? The Gauge for example seems to support floats including the increment methods.

Thanks!

**Comment by rdohms** [comment]
It would appear the Go docs agree that counter can be floats: https://godoc.org/github.com/prometheus/client_golang/prometheus#Counter as does the Java implementation https://github.com/prometheus/client_java/blob/master/simpleclient/src/main/java/io/prometheus/client/Counter.java#L121

I see no reason to not go ahead and fix this.

**Comment by rdohms** [comment]
First run through shows that `apcu_inc` does not support floats, so it needs a bit more re-work (https://www.php.net/manual/en/function.apcu-inc.php)

**Comment by LKaemmerling** [comment]
I guess the best way would be dropping the usage of `apcu_inc` and using `acpu_store` (https://www.php.net/manual/en/function.apcu-store.php). I will look into it if this changes the behavior we have currently. I don't think that it changes the behavior but we need to make sure, that we don't break things.
