### ISSUE TITLE
APC Adapter hangs if APCu is disabled

### ISSUE THREAD

**Issue by encero** [PromPHP/prometheus_client_php#27]
Hello, i want to discuss possible solutions for "issue" with APC Adapter.

If CollectorResgistry is instantiated with APC adapter and apcu is not enabled, any call to observe metrics will hang in endless loop. For instance in this snippet from updateHistogram.

apcu_fetch and apcu_cas returns `false` when apcu is disabled, so the `!$done` condition is never met.

```php
public function updateHistogram(array $data): void {
...
        while (!$done) {
            $old = apcu_fetch($sumKey);
            if ($old !== false) {
                $done = apcu_cas($sumKey, $old, $this->toBinaryRepresentationAsInteger($this->fromBinaryRepresentationAsInteger($old) + $data['value']));
            }
        }
}
```

Possible solutions from my standpoint:
1. check apcu_enabled in APC Adapter constructor and throw exception
2. limit max interation count

I can make the changes myself, just want to make agreement with maintainers on right approach

Story time: our CI pipelines was stuck on tests because of this ( disabled apcu in CLI )

**Comment by LKaemmerling** [comment]
I guess solution 1. would be great, as the APCU is a hard requirement and it should be enabled. The same is valid for the Redis Storage adapter (with redis of course).

It would be great if you have the time to solve it and contribute a fix :) We are open for everything and will look into it as fast as possible.

**Comment by LKaemmerling** [comment]
@encero a big thank you for your improvements. I just released a new version with your fixes :) 
https://github.com/PromPHP/prometheus_client_php/releases/tag/v2.2.1
