### ISSUE TITLE
Invalid metrics name are stored to backend but cannot be read by prometheus

### ISSUE THREAD

**Issue by boesing** [PromPHP/prometheus_client_php#40]
Hey there,

I've recently added a metric name containing a `-` in it. Sadly, the client stores it to the backend and adds it to the meta and now I cannot easily remove the metric from the backend because there is that `PROMETHEUS_histogram_METRIC_KEYS` key containing all available keys...

So I'd like to feature request some kind of metric name validation so it is impossible to store keys not matching the regex from prometheus:

`[a-zA-Z_:][a-zA-Z0-9_:]`

https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels

**Comment by LKaemmerling** [comment]
Hey @boesing,

good idea! I will open up a MR with this change shortly.

**Comment by boesing** [comment]
Would have done that by myself but later on. But sure, if you're adding it, that would be appreciated.

**Comment by boesing** [comment]
It seems that there is already some validation in the `Collector` abstract class, but we are using the adapter interface directly and thus the validation is missing.

**Comment by LKaemmerling** [comment]
> It seems that there is already some validation in the `Collector` abstract class, but we are using the adapter interface directly and thus the validation is missing.
> I've implemented the validation on our side, not sure if its _really_ necessary to add it to the adapters aswell as we are obviously not using this library as it should be used. 😅

Yeah this is a "problem". But actually I still think that it is validated on the wrong layer. It should be validated in the Registry aswell.

**Comment by boesing** [comment]
Well, we are just calling the `Adapter` as we do not want to depend on concrete implementations. 
We want to switch to `Statsd` later on, thus we abstracted this library in a domain interface which then directly passes metrics to the prometheus `Adapter`.

Thats why I've added the validation on our side but I just wanted to trigger awareness that there is still code which passes the metric to the storage backend without validating the metrics name/label. 👍🏼

**Comment by LKaemmerling** [comment]
@boesing i just opened up an MR: https://github.com/PromPHP/prometheus_client_php/pull/41 

basically, it is not a real fix, as I think we shouldn't validate everything on every layer. As you said you use the storage adapters in an unintended way, so I just added methods to validate the metric names & label keys easily.
