### ISSUE TITLE
BC break in v2.2.2

### ISSUE THREAD

**Issue by oqq** [PromPHP/prometheus_client_php#43]
Hi Folks!

The version v2.2.2 adds a new method `wipeStorage()` to the `Adapter` interface.
This breaks all implementations in private libraries, which is hard move for a patch release.

Maybe this method should be removed for all v2 releases and added again in a major v3 release.

greetings!

**Comment by LKaemmerling** [comment]
Hey @oqq,

I understand your concerns about the change, but unfortunately, I wouldn't call this a Breaking Change. It is a bugfix for the existing Storage Adapters and we encourage all users to use the given StorageAdapters. 

I'm unsure if we should really remove that functionality again, as I don't see the benefit of removing this again and having a partly broken deletion there.

Commit that introduced it:
https://github.com/PromPHP/prometheus_client_php/commit/28d4ad43752415fae8b346f6b54bf7caaf514c55

I also think that we never can test all implementations of the Storage Adapter interface out in the wild, the interface is mostly for internal organization.

**Comment by oqq** [comment]
Hey @LKaemmerling,

thanks for your fast reply.

This issue is not about the new functionality. Previously the documentation has referred to now deprecated methods for storage clearance. So maybe it would be enough to reference this new method without adding it to the interface.

So if this interface is not meant to be used from other libraries, a "@internal" annotation would be nice.

I fully understood the trouble to revert this commit and will add this method to my implementation.
But please consider this semver basics before releasing code with bc breaks.
Adding a new method to a public interface is a breaking change with no doubt.

I am fine if this issue would be closed. :)

**Comment by LKaemmerling** [comment]
Hey @oqq,

you are completely right, i will look more deeper in the changes that they follow semver before releasing everything. Thank you! I think I learned my lessons about it :) 

I will close the issue for now :)
