### ISSUE TITLE
Redis Persistenet Connection Default Value

### ISSUE THREAD

**Issue by hamed-fo** [PromPHP/prometheus_client_php#49]
Hello,
In Redis class the default value for `persistent_connections` is set to `False` while in `connectToServer` method it is compared against `null`. So persistent connections are made by default which probably is not the desired behavior (according to the default value of `persistent_connections`).

**Comment by LKaemmerling** [comment]
Hey @hamed-fo,

yep, you are right, this does not look correct. Do you want to submit a Pull Request :)? Otherwise, I would submit a fix within this week.

Cheers,
Lukas
