### ISSUE TITLE
Add Summary Metric Type

### ISSUE THREAD

**Issue by LKaemmerling** [PromPHP/prometheus_client_php#6]
Similar to a histogram, a summary samples observations (usually things like request durations and response sizes). While it also provides a total count of observations and a sum of all observed values, it calculates configurable quantiles over a sliding time window.

A summary with a base metric name of <basename> exposes multiple time series during a scrape:

streaming φ-quantiles (0 ≤ φ ≤ 1) of observed events, exposed as <basename>{quantile="<φ>"}
the total sum of all observed values, exposed as <basename>_sum
the count of events that have been observed, exposed as <basename>_count
See histograms and summaries for detailed explanations of φ-quantiles, summary usage, and differences to histograms.

https://prometheus.io/docs/concepts/metric_types/#summary

**Comment by mp3000mp** [comment]
Hi @LKaemmerling, is it a feature you'll be interested to include in this library ? 

If yes, I would be glad to work on a PR inspired by the [Java](https://github.com/prometheus/client_java/) and [Go](https://github.com/prometheus/client_golang) implementations.

**Comment by LKaemmerling** [comment]
Hey @mp3000mp,

sure :) Feel free to work on a MR and i will look over it.
