### ISSUE TITLE
Missing tags for last merges

### ISSUE THREAD

**Issue by cwreden** [PromPHP/prometheus_client_php#66]
Hello together,

since v2.2.2 there are no tags for the latest merges.
Is it possible to tag the latest merges?

We don't want using the "dev-master" as dependency.

https://github.com/PromPHP/prometheus_client_php/commits/master

Best regards
Christian

**Comment by LKaemmerling** [comment]
Hey @cwreden,

i just released v2.3.0 with the last changes :)
