### ISSUE TITLE
Breaking Changes along the way

### ISSUE THREAD

**Issue by bburnichon** [PromPHP/prometheus_client_php#87]
Hello, I came by this fork migrating a project from using `endclothing/prometheus_client_php` to latest php 8.1 version. Thanks for your hard work

Along the way, #31 & #53 were merged and considered as adding features and so, bumping minor of the package.

Troubles come from adding method to public interfaces, namely `Prometheus\Storage\Adapter`. Each of this addition breaks an homemade Storage adapter (with a backend similar to redis but with different limitations).

**Comment by LKaemmerling** [comment]
Hey,

The Storage Apdater Interface is not part of the Public API. It is part of the private API, and is used to unify the own StorageEngines (Redis & Co).  Therefore this is not considered a Breaking Change, as the Collector (which is the Public API) was not changed.
