### ISSUE TITLE
keys/scan redis commands shouldn't be used

### ISSUE THREAD

**Issue by stefanoparkopedia** [PromPHP/prometheus_client_php#90]
I've upgraded to Laravel 8 and the performance was poor;  digging into it I found out that `$registry->getMetricFamilySamples()`, when using the Redis adapter, uses the `keys` Redis command that's a performance killer (redis is single-threaded).

https://github.com/PromPHP/prometheus_client_php/blob/10881142d2c55de19f529ebbcb7f89558c6d46d4/src/Prometheus/Storage/Redis.php#L488

**Comment by ikhabitoff** [comment]
We also met with a similar problem. Radis recommends using scan instead of keys when looking for keys. I tried to replace the method without breaking the library tests and created pull request. You can try to use my solution temporarily. #91

**Comment by LKaemmerling** [comment]
Hey,

thanks to @ikhabitoff who fixed it :) The release with the fix was just tagged (2.6.1).
