### ISSUE TITLE
Missing compose and other essential libs in php-fpm/Dockerfile

### ISSUE THREAD

**Issue by RomanOrlovDev** [PromPHP/prometheus_client_php#97]
Hi Guys,

just wondering - how do you install composer dependencies for the project if composer itself missing in the image that built from php-fpm/Dockerfile? 

Also zip extensions are missing there

**Comment by LKaemmerling** [comment]
Hey @RomanOrlovDev,

this is used just in our Blackbox tests. It is build in the docker-compose file in the root folder and basically just there to have a basic web server to perform tests against :)

**Comment by RomanOrlovDev** [comment]
Got it!
